# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/BrightLand/Envy/_opencv/modules/dnn/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/BrightLand/Envy/_opencv/modules/dnn/cmake/hooks/INIT_MODULE_SOURCES_opencv_dnn.cmake))

/Users/BrightLand/Envy/OpenCV/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -H/Users/BrightLand/Envy/_opencv -B/Users/BrightLand/Envy/OpenCV
