# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/BrightLand/Envy/_opencv/modules/core/misc/python/package/mat_wrapper/__init__.py))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/BrightLand/Envy/_opencv/modules/core/misc/python/package/utils/__init__.py))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/BrightLand/Envy/_opencv/modules/gapi/misc/python/package/gapi/__init__.py))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/BrightLand/Envy/_opencv/modules/python/bindings/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/BrightLand/Envy/_opencv/modules/python/package/cv2/__init__.py))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/BrightLand/Envy/_opencv/modules/python/package/cv2/load_config_py2.py))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/BrightLand/Envy/_opencv/modules/python/package/cv2/load_config_py3.py))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/BrightLand/Envy/_opencv/modules/python/package/extra_modules/misc/__init__.py))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/BrightLand/Envy/_opencv/modules/python/package/extra_modules/misc/version.py))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/BrightLand/Envy/_opencv/modules/python/package/setup.py))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/BrightLand/Envy/_opencv/modules/python/package/template/config.py.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/BrightLand/Envy/_opencv/modules/python/python_loader.cmake))

/Users/BrightLand/Envy/OpenCV/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -H/Users/BrightLand/Envy/_opencv -B/Users/BrightLand/Envy/OpenCV
