# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/BrightLand/Envy/_opencv/modules/core/misc/java/src/java/core+Core.jcode.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/BrightLand/Envy/_opencv/modules/java/common.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/BrightLand/Envy/_opencv/modules/java/generator/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/BrightLand/Envy/_opencv/modules/java/generator/android/java/org/opencv/android/OpenCVLoader.java.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/BrightLand/Envy/_opencv/modules/java/generator/src/java/org/opencv/osgi/OpenCVNativeLoader.java.in))

/Users/BrightLand/Envy/OpenCV/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -H/Users/BrightLand/Envy/_opencv -B/Users/BrightLand/Envy/OpenCV
